    # We want to extend the system.site configuration
    system.site:
      mapping:
        # Our field name is 'description'
        description:
          type: string
          label: 'Site Description'